In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy import linalg as LA 

In [156]:
def computeSVD(A):
    #1. Compute matrix tranpose
    shapeA = A.shape
    A_t = A.transpose()
    A = A_t
    print(A_t)
    #2. Determine the eigenvalues of AA_t and A_tA
    AA_t = A@A_t
    A_tA = A_t@A
    AA_tvalues, AA_tvector = LA.eig(AA_t)
    A_tAvalues, A_tAvector = LA.eig(A_tA)
    print('1',AA_tvector)
    print('2',A_tAvector)
    #square root the eigenvalues of A_tA to obtain the absolute values of A
    s_i_values1 = []
    s_i_values2 = []
    for value in AA_tvalues:
        s_i_values1.append(np.sqrt(value))
    for value in A_tAvalues:
        print(value)
        s_i_values2.append(np.sqrt(value))
    #construct diagonal matrix  S by placing the singular values along the diagonal in descending order
    S_1 = np.zeros(shapeA)
    S_2 = np.zeros(shapeA)
    
    np.fill_diagonal(S_1, s_i_values1)
    np.fill_diagonal(S_2, s_i_values2)

    #place eigenvectors of A_tA along the columns of V and compute its tranpose 
    #S_inv = np.linalg.inv(S)
    print(A_tAvector)
    V = np.stack(A_tAvector,axis=-1)
    V_t = V.transpose()
    print(V)
    #computer U as U=AVS^-1
    U = np.stack(AA_tvector,axis = -1)
    U = U.transpose()
    return U@S_2@V_t

In [66]:
A = np.array([[2,4],[1,3],[0,0],[0,0]])
#define matrix tranpose
A_t = A.transpose()
#compute products
A_tA = A_t @ A
AA_t = A @ A_t     

In [67]:
A_tA

array([[ 5, 11],
       [11, 25]])

In [68]:
#compute eigenvalues and vectors
AA_tvalues, AA_tvector = LA.eig(AA_t)
A_tAvalues, A_tAvector = LA.eig(A_tA)

In [69]:
AA_tvalues

array([29.86606875,  0.13393125,  0.        ,  0.        ])

In [70]:
AA_tvector

array([[ 0.81741556, -0.57604844,  0.        ,  0.        ],
       [ 0.57604844,  0.81741556,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [72]:
A_tAvalues

array([ 0.13393125, 29.86606875])

In [71]:
A_tAvector

array([[-0.9145143 , -0.40455358],
       [ 0.40455358, -0.9145143 ]])

In [57]:
matrixShape = A.shape 
S = np.zeros(matrixShape)
sigma_i = []
for value in A_tAvalues:
    sigma_i.append(np.sqrt(value))
np.fill_diagonal(S, sigma_i)

In [58]:
S

array([[0.36596619, 0.        ],
       [0.        , 5.4649857 ],
       [0.        , 0.        ],
       [0.        , 0.        ]])

In [59]:
#construct v vectors and v arrays 
v1 = np.array((A_tAvector[0][0],A_tAvector[1][0]))
v2 = np.array((A_tAvector[0][1],A_tAvector[1][1]))
V = np.column_stack((v1,v2))

In [60]:
sigma1u1 = A @ v1
sigma2u2 = A @ v2

In [61]:
u1 = sigma1u1/sigma_i[0]
u2 = sigma2u2/sigma_i[1]

In [62]:
U = np.column_stack((u1,u2))

In [63]:
U

array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [64]:
V_t = V.transpose()

In [65]:
U @ S @ V_t

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [52]:
def computeSVD(A):
#define matrix tranpose
    A_t = A.transpose()
#compute products
    A_tA = A_t @ A
    AA_t = A @ A_t     
#compute eigenvalues and vectors
    AA_tvalues, AA_tvector = LA.eig(AA_t)
    A_tAvalues, A_tAvector = LA.eig(A_tA)
#define and fill S (diagonal) matrix 
    matrixShape = A.shape 
    S = np.zeros(matrixShape)
    sigma_i = []
    for value in A_tAvalues:
        sigma_i.append(np.sqrt(value))
    sigma_i.sort(reverse = True)
    np.fill_diagonal(S, sigma_i)    
    print('S= ', S)
#construct v vectors and v arrays
    v_i = []
    for i in range(len(A_tAvector)):
        v_i.append(A_tAvector[i])
    V = np.column_stack((A_tAvector)) 
    V_t = V.transpose()
    print('V= ', V)
    print('V_t=  ',V_t)
    sigma_iu_i = []
    for value in v_i:
        sigma_iu_i.append(A @ value)
    u_i = []
    for i in range(len(sigma_iu_i)):
        ui = sigma_iu_i[i]/sigma_i[i]
        u_i.append(ui)
    U = np.column_stack((u_i))
    print('U= ',U)
    print(U.shape)
    print(S.shape)
    return U @ S @ V_t

In [54]:
A = np.array([[2,4,3],[1,3,3],[0,5,6]])

In [55]:
computeSVD(A)

S=  [[10.24844096  0.          0.        ]
 [ 0.          1.98689506  0.        ]
 [ 0.          0.          0.14732909]]
V=  [[-0.13972804 -0.68794948 -0.71218087]
 [-0.86360659 -0.26719423  0.42754054]
 [ 0.48441691 -0.67478349  0.55678317]]
V_t=   [[-0.13972804 -0.86360659  0.48441691]
 [-0.68794948 -0.26719423 -0.67478349]
 [-0.71218087  0.42754054  0.55678317]]
U=  [[-0.2225345  -2.24925132 13.27741767]
 [-0.12463331 -1.76852955 15.20942121]
 [-0.13773134 -2.71009385 37.18479181]]
(3, 3)
(3, 3)


array([[2.00000000e+00, 4.00000000e+00, 3.00000000e+00],
       [1.00000000e+00, 3.00000000e+00, 3.00000000e+00],
       [5.17796884e-16, 5.00000000e+00, 6.00000000e+00]])

# Reduced SVD 

This is the case where rank(A) = numCols(U) = numCols(V)

In [84]:
HA_tAvector = LA.eig(A_tA)
    
#define and fill S (diagonal) matrix 
    matrixShape = A.shape 
   # S = np.zeros((rank,rank))
    sigma_i = []
    for value in AA_tvalues:
        print('value i: ', value)
        sigma_i.append(np.sqrt(value))
    sigma_i.sort(reverse = True)
    print('sigma_i', sigma_i)
    #np.fill_diagonal(S, sigma_i) 
    S = np.diag(sigma_i)
    print('S= ', S)
#construct v vectors and v arrays
    v_i = []
    print('A_tAvector = ', A_tAvector)
    for i in range(2):
        v_i.append(A_tAvector[i])
    print('v_i',v_i)
    V = np.column_stack((v_i))
    
    V_t = V.transpose()
    print('V= ', V)
    print('V_t=  ',V_t)
    sigma_iu_i = []
    for value in v_i:
        sigma_iu_i.append(A @ value)
    u_i = []
    for i in range(len(sigma_i)):
        ui = sigma_iu_i[i]/sigma_i[i]
        u_i.append(ui)
    U = np.column_stack((u_i))
    print('U= ',U)
    print(U.shape)
    print(S.shape)
    return U @ S @ V_t

In [85]:
A = np.array([[1,2,3,4],[0,1,6,5]])
print(A)
computeReducedSVD(A)

[[1 2 3 4]
 [0 1 6 5]]
rank=  2
value i:  2.91868154292397
value i:  89.08131845707604
sigma_i [9.438290017639638, 1.7084149211839523]
S=  [[9.43829002 0.        ]
 [0.         1.70841492]]
A_tAvector =  [[-0.0593994   0.48469913 -0.3290523   0.07131028]
 [-0.20653369  0.64124098 -0.45279249 -0.66771595]
 [-0.70460749 -0.51484634 -0.48466849 -0.40552715]
 [-0.67627201  0.29801008  0.67216069  0.62017577]]
v_i [array([-0.0593994 ,  0.48469913, -0.3290523 ,  0.07131028]), array([-0.20653369,  0.64124098, -0.45279249, -0.66771595])]
V=  [[-0.0593994  -0.20653369]
 [ 0.48469913  0.64124098]
 [-0.3290523  -0.45279249]
 [ 0.07131028 -0.66771595]]
V_t=   [[-0.0593994   0.48469913 -0.3290523   0.07131028]
 [-0.20653369  0.64124098 -0.45279249 -0.66771595]]
U=  [[ 0.02204669 -1.72867433]
 [-0.12004963 -3.16907425]]
(2, 2)
(2, 2)


array([[ 0.59759449, -1.79291481,  1.26875869,  1.98679933],
       [ 1.18549603, -4.02093354,  2.82429806,  3.53427771]])

In [87]:
A_t = A.transpose()
A_tA = A_t@A
AA_t = A@A_t
A_tAeigs, A_tAeigvec = LA.eig(A_tA)
AA_teigs, AA_teigvec = LA.eig(AA_t) 

In [88]:
A_tAeigvec

array([[-0.0593994 ,  0.48469913, -0.3290523 ,  0.07131028],
       [-0.20653369,  0.64124098, -0.45279249, -0.66771595],
       [-0.70460749, -0.51484634, -0.48466849, -0.40552715],
       [-0.67627201,  0.29801008,  0.67216069,  0.62017577]])

In [89]:
a = np.array([[1,2,3,4],[0,1,6,5]])
U, s, V = np.linalg.svd(a)

In [90]:
U

array([[-0.56062881, -0.82806723],
       [-0.82806723,  0.56062881]])

In [97]:
s
S = np.diag(s)

In [96]:
V
V_t = V.transpose()

In [98]:
U @ S @ V_t

ValueError: shapes (2,2) and (4,4) not aligned: 2 (dim 1) != 4 (dim 0)

In [112]:
def letsTryThisAgainFolks(A):
    A_t = A.transpose()
    rank = np.linalg.matrix_rank(A)
    m,n = A.shape
    maxi = max(m,n)
    #full rank SVD calculation
    if (rank == maxi or rank == maxi):
        U, s, V = np.linalg.svd(A)
        S = np.diag(s)
        V_t = V.transpose()
    if (rank < maxi):
        U, s, V = np.linalg.svd(A, full_matrices = False)
        S = np.diag(s)
        V_t = V.transpose()
    print(U)
    print(S)
    print(V_t)
    return U @ S @ V_t

In [113]:
letsTryThisAgainFolks(A)

[[-0.56062881 -0.82806723]
 [-0.82806723  0.56062881]]
[[9.43829002 0.        ]
 [0.         1.70841492]]
[[-0.0593994  -0.48469913]
 [-0.20653369 -0.64124098]
 [-0.70460749  0.51484634]
 [-0.67627201 -0.29801008]]


ValueError: shapes (2,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)